<?php

$text['title-tts-recordings']['en-us'] = "TTS Recordings";
$text['title-tts-recordings']['en-gb'] = "TTS Recordings";
$text['title-tts-recordings']['es-cl'] = "";
$text['title-tts-recordings']['pt-pt'] = "";
$text['title-tts-recordings']['fr-fr'] = "";
$text['title-tts-recordings']['pt-br'] = "";
$text['title-tts-recordings']['pl'] = "";
$text['title-tts-recordings']['sv-se'] = "";
$text['title-tts-recordings']['uk'] = "";
$text['title-tts-recordings']['de-at'] = "";

$text['title-tts-recording']['en-us'] = "Text to Speech Recording";
$text['title-tts-recording']['en-gb'] = "Text to Speech Recording";
$text['title-tts-recording']['es-cl'] = "";
$text['title-tts-recording']['pt-pt'] = "";
$text['title-tts-recording']['fr-fr'] = "";
$text['title-tts-recording']['pt-br'] = "";
$text['title-tts-recording']['pl'] = "";
$text['title-tts-recording']['sv-se'] = "";
$text['title-tts-recording']['uk'] = "";
$text['title-tts-recording']['de-at'] = "";

$text['description-tts-recordings']['en-us'] = "Text to Speech Recordings, created using Microsoft Azure Cognitive Speech Services.";
$text['description-tts-recordings']['en-gb'] = "Text to Speech Recordings, created using Microsoft Azure Cognitive Speech Services.";
$text['description-tts-recordings']['es-cl'] = "";
$text['description-tts-recordings']['pt-pt'] = "";
$text['description-tts-recordings']['fr-fr'] = "";
$text['description-tts-recordings']['pt-br'] = "";
$text['description-tts-recordings']['pl'] = "";
$text['description-tts-recordings']['sv-se'] = "";
$text['description-tts-recordings']['uk'] = "";
$text['description-tts-recordings']['de-at'] = "";

$text['label-tools']['en-us'] = "Tools";
$text['label-tools']['en-gb'] = "Tools";
$text['label-tools']['ar-eg'] = "";
$text['label-tools']['de-at'] = "Funktionen"; //copied from de-de
$text['label-tools']['de-ch'] = "Funktionen"; //copied from de-de
$text['label-tools']['de-de'] = "Funktionen";
$text['label-tools']['es-cl'] = "Instrumentos";
$text['label-tools']['es-mx'] = "Instrumentos"; //copied from es-cl
$text['label-tools']['fr-ca'] = "Outils"; //copied from fr-fr
$text['label-tools']['fr-fr'] = "Outils";
$text['label-tools']['he-il'] = "כלים";
$text['label-tools']['it-it'] = "Strumenti";
$text['label-tools']['nl-nl'] = "Gereedschappen";
$text['label-tools']['pl-pl'] = "Narzędzia";
$text['label-tools']['pt-br'] = "Ferramentas"; //copied from pt-pt
$text['label-tools']['pt-pt'] = "Ferramentas";
$text['label-tools']['ro-ro'] = "";
$text['label-tools']['ru-ru'] = "Инструменты";
$text['label-tools']['sv-se'] = "Verktyg";
$text['label-tools']['uk-ua'] = "Параметри";

$text['label-recording_name']['en-us'] = "Recording Name";
$text['label-recording_name']['en-gb'] = "Recording Name";
$text['label-recording_name']['ar-eg'] = "";
$text['label-recording_name']['de-at'] = "Name der Aufnahme"; //copied from de-de
$text['label-recording_name']['de-ch'] = "Name der Aufnahme"; //copied from de-de
$text['label-recording_name']['de-de'] = "Name der Aufnahme";
$text['label-recording_name']['es-cl'] = "Nombre de la grabación";
$text['label-recording_name']['es-mx'] = "Nombre de la grabación"; //copied from es-cl
$text['label-recording_name']['fr-ca'] = "Nom de l'enregistrement"; //copied from fr-fr
$text['label-recording_name']['fr-fr'] = "Nom de l'enregistrement";
$text['label-recording_name']['he-il'] = "שם הקובץ מדיה";
$text['label-recording_name']['it-it'] = "Nome Registrazione";
$text['label-recording_name']['nl-nl'] = "Opnamenaam";
$text['label-recording_name']['pl-pl'] = "Nazwa nagrania";
$text['label-recording_name']['pt-br'] = "Nome da gravação"; //copied from pt-pt
$text['label-recording_name']['pt-pt'] = "Nome da gravação";
$text['label-recording_name']['ro-ro'] = "";
$text['label-recording_name']['ru-ru'] = "Название записи";
$text['label-recording_name']['sv-se'] = "Namn på inspelning";
$text['label-recording_name']['uk-ua'] = "Назва запису";

$text['label-play']['en-us'] = "Play";
$text['label-play']['en-gb'] = "Play";
$text['label-play']['ar-eg'] = "";
$text['label-play']['de-at'] = "Abspielen"; //copied from de-de
$text['label-play']['de-ch'] = "Abspielen"; //copied from de-de
$text['label-play']['de-de'] = "Abspielen";
$text['label-play']['es-cl'] = "Reproducir";
$text['label-play']['es-mx'] = "Reproducir"; //copied from es-cl
$text['label-play']['fr-ca'] = "Jouer"; //copied from fr-fr
$text['label-play']['fr-fr'] = "Jouer";
$text['label-play']['he-il'] = "נגן";
$text['label-play']['it-it'] = "Riproduci";
$text['label-play']['nl-nl'] = "Afspelen";
$text['label-play']['pl-pl'] = "Odtwórz";
$text['label-play']['pt-br'] = "Tocar"; //copied from pt-pt
$text['label-play']['pt-pt'] = "Tocar";
$text['label-play']['ro-ro'] = "";
$text['label-play']['ru-ru'] = "Проиграть";
$text['label-play']['sv-se'] = "Spela Upp";
$text['label-play']['uk-ua'] = "Відтворити";

$text['label-pause']['en-us'] = "Pause";
$text['label-pause']['en-gb'] = "Pause";
$text['label-pause']['ar-eg'] = "";
$text['label-pause']['de-at'] = "Pause"; //copied from de-de
$text['label-pause']['de-ch'] = "Pause"; //copied from de-de
$text['label-pause']['de-de'] = "Pause";
$text['label-pause']['es-cl'] = "Pausa";
$text['label-pause']['es-mx'] = "Pausa"; //copied from es-cl
$text['label-pause']['fr-ca'] = "Pause"; //copied from fr-fr
$text['label-pause']['fr-fr'] = "Pause";
$text['label-pause']['he-il'] = "השהה";
$text['label-pause']['it-it'] = "Pausa";
$text['label-pause']['nl-nl'] = "Pauze";
$text['label-pause']['pl-pl'] = "Pauza";
$text['label-pause']['pt-br'] = "Pausado";
$text['label-pause']['pt-pt'] = "Pausa";
$text['label-pause']['ro-ro'] = "";
$text['label-pause']['ru-ru'] = "Пайза";
$text['label-pause']['sv-se'] = "Paus";
$text['label-pause']['uk-ua'] = "Призупинити";

$text['label-file_name']['en-us'] = "File Name";
$text['label-file_name']['en-gb'] = "File Name";
$text['label-file_name']['ar-eg'] = "";
$text['label-file_name']['de-at'] = "Dateiname"; //copied from de-de
$text['label-file_name']['de-ch'] = "Dateiname"; //copied from de-de
$text['label-file_name']['de-de'] = "Dateiname";
$text['label-file_name']['es-cl'] = "Nombre del Archivo";
$text['label-file_name']['es-mx'] = "Nombre del Archivo"; //copied from es-cl
$text['label-file_name']['fr-ca'] = "Nom du Fichier"; //copied from fr-fr
$text['label-file_name']['fr-fr'] = "Nom du Fichier";
$text['label-file_name']['he-il'] = "שם קובץ מדיה";
$text['label-file_name']['it-it'] = "Nome File";
$text['label-file_name']['nl-nl'] = "Bestandsnaam";
$text['label-file_name']['pl-pl'] = "Nazwa pliku";
$text['label-file_name']['pt-br'] = "Nome do arquivo";
$text['label-file_name']['pt-pt'] = "Nome do Arquivo";
$text['label-file_name']['ro-ro'] = "";
$text['label-file_name']['ru-ru'] = "Имя файла";
$text['label-file_name']['sv-se'] = "Fil-namn";
$text['label-file_name']['uk-ua'] = "Назва файлу";

$text['label-download']['en-us'] = "Download";
$text['label-download']['en-gb'] = "Download";
$text['label-download']['ar-eg'] = "";
$text['label-download']['de-at'] = "Herunterladen"; //copied from de-de
$text['label-download']['de-ch'] = "Herunterladen"; //copied from de-de
$text['label-download']['de-de'] = "Herunterladen";
$text['label-download']['es-cl'] = "Descargar";
$text['label-download']['es-mx'] = "Descargar"; //copied from es-cl
$text['label-download']['fr-ca'] = "Télécharger"; //copied from fr-fr
$text['label-download']['fr-fr'] = "Télécharger";
$text['label-download']['he-il'] = "הורדה";
$text['label-download']['it-it'] = "Scaricare";
$text['label-download']['nl-nl'] = "Ophalen";
$text['label-download']['pl-pl'] = "Pobierz";
$text['label-download']['pt-br'] = "Download";
$text['label-download']['pt-pt'] = "Descarregar";
$text['label-download']['ro-ro'] = "";
$text['label-download']['ru-ru'] = "Загрузить";
$text['label-download']['sv-se'] = "Ladda Ned";
$text['label-download']['uk-ua'] = "Завантажини";

$text['label-recording_voice']['en-us'] = "Voice";
$text['label-recording_voice']['en-gb'] = "Voice";
$text['label-recording_voice']['es-cl'] = "";
$text['label-recording_voice']['pt-pt'] = "";
$text['label-recording_voice']['fr-fr'] = "";
$text['label-recording_voice']['pt-br'] = "";
$text['label-recording_voice']['pl'] = "";
$text['label-recording_voice']['sv-se'] = "";
$text['label-recording_voice']['uk'] = "";
$text['label-recording_voice']['de-at'] = "";

$text['label-is_text_ssml']['en-us'] = "Is Text SSML";
$text['label-is_text_ssml']['en-gb'] = "Is Text SSML";
$text['label-is_text_ssml']['es-cl'] = "";
$text['label-is_text_ssml']['pt-pt'] = "";
$text['label-is_text_ssml']['fr-fr'] = "";
$text['label-is_text_ssml']['pt-br'] = "";
$text['label-is_text_ssml']['pl'] = "";
$text['label-is_text_ssml']['sv-se'] = "";
$text['label-is_text_ssml']['uk'] = "";
$text['label-is_text_ssml']['de-at'] = "";

$text['label-recording_text']['en-us'] = "Text";
$text['label-recording_text']['en-gb'] = "Text";
$text['label-recording_text']['es-cl'] = "";
$text['label-recording_text']['pt-pt'] = "";
$text['label-recording_text']['fr-fr'] = "";
$text['label-recording_text']['pt-br'] = "";
$text['label-recording_text']['pl'] = "";
$text['label-recording_text']['sv-se'] = "";
$text['label-recording_text']['uk'] = "";
$text['label-recording_text']['de-at'] = "";

$text['label-pitch']['en-us'] = "Voice Pitch";
$text['label-pitch']['en-gb'] = "Voice Pitch";
$text['label-pitch']['es-cl'] = "";
$text['label-pitch']['pt-pt'] = "";
$text['label-pitch']['fr-fr'] = "";
$text['label-pitch']['pt-br'] = "";
$text['label-pitch']['pl'] = "";
$text['label-pitch']['sv-se'] = "";
$text['label-pitch']['uk'] = "";
$text['label-pitch']['de-at'] = "";

$text['label-speaking_rate']['en-us'] = "Speaking Rate";
$text['label-speaking_rate']['en-gb'] = "Speaking Rate";
$text['label-speaking_rate']['es-cl'] = "";
$text['label-speaking_rate']['pt-pt'] = "";
$text['label-speaking_rate']['fr-fr'] = "";
$text['label-speaking_rate']['pt-br'] = "";
$text['label-speaking_rate']['pl'] = "";
$text['label-speaking_rate']['sv-se'] = "";
$text['label-speaking_rate']['uk'] = "";
$text['label-speaking_rate']['de-at'] = "";

$text['label-generated_ssml']['en-us'] = "Generated SSML";
$text['label-generated_ssml']['en-gb'] = "Generated SSML";
$text['label-generated_ssml']['es-cl'] = "";
$text['label-generated_ssml']['pt-pt'] = "";
$text['label-generated_ssml']['fr-fr'] = "";
$text['label-generated_ssml']['pt-br'] = "";
$text['label-generated_ssml']['pl'] = "";
$text['label-generated_ssml']['sv-se'] = "";
$text['label-generated_ssml']['uk'] = "";
$text['label-generated_ssml']['de-at'] = "";

$text['label-highlight']['en-us'] = "Speech Synthesis Preview";
$text['label-highlight']['en-gb'] = "Speech Synthesis Preview";
$text['label-highlight']['es-cl'] = "";
$text['label-highlight']['pt-pt'] = "";
$text['label-highlight']['fr-fr'] = "";
$text['label-highlight']['pt-br'] = "";
$text['label-highlight']['pl'] = "";
$text['label-highlight']['sv-se'] = "";
$text['label-highlight']['uk'] = "";
$text['label-highlight']['de-at'] = "";

$text['label-date_created']['en-us'] = "Created";
$text['label-date_created']['en-gb'] = "Created";
$text['label-date_created']['es-cl'] = "";
$text['label-date_created']['pt-pt'] = "";
$text['label-date_created']['fr-fr'] = "";
$text['label-date_created']['pt-br'] = "";
$text['label-date_created']['pl'] = "";
$text['label-date_created']['sv-se'] = "";
$text['label-date_created']['uk'] = "";
$text['label-date_created']['de-at'] = "";

$text['label-date_updated']['en-us'] = "Last Updated";
$text['label-date_updated']['en-gb'] = "Last Updated";
$text['label-date_updated']['es-cl'] = "";
$text['label-date_updated']['pt-pt'] = "";
$text['label-date_updated']['fr-fr'] = "";
$text['label-date_updated']['pt-br'] = "";
$text['label-date_updated']['pl'] = "";
$text['label-date_updated']['sv-se'] = "";
$text['label-date_updated']['uk'] = "";
$text['label-date_updated']['de-at'] = "";

$text['label-edit-recording_name']['en-us'] = "Please provide: Recording Name";
$text['label-edit-recording_name']['en-gb'] = "Please provide: Recording Name";
$text['label-edit-recording_name']['ar-eg'] = "";
$text['label-edit-recording_name']['de-at'] = "Bitte geben Sie folgendes an: Name der Aufnahme"; //copied from de-de
$text['label-edit-recording_name']['de-ch'] = "Bitte geben Sie folgendes an: Name der Aufnahme"; //copied from de-de
$text['label-edit-recording_name']['de-de'] = "Bitte geben Sie folgendes an: Name der Aufnahme";
$text['label-edit-recording_name']['es-cl'] = "Por favor indique: Nombre de la grabación";
$text['label-edit-recording_name']['es-mx'] = "Por favor indique: Nombre de la grabación"; //copied from es-cl
$text['label-edit-recording_name']['fr-ca'] = "Merci d'indiquer: nom de l'enregistrement"; //copied from fr-fr
$text['label-edit-recording_name']['fr-fr'] = "Merci d'indiquer: nom de l'enregistrement";
$text['label-edit-recording_name']['he-il'] = "אנא ספק: הקלטת שם הפעלה";
$text['label-edit-recording_name']['it-it'] = "Prego fornire: Nome Registrazione";
$text['label-edit-recording_name']['nl-nl'] = "Geef aub.: Opename naam";
$text['label-edit-recording_name']['pl-pl'] = "Wprowadź: Nazwę nagrania";
$text['label-edit-recording_name']['pt-br'] = "Por favor indique: Nome da gravação";
$text['label-edit-recording_name']['pt-pt'] = "Por favor indique: Nome da Gravação";
$text['label-edit-recording_name']['ro-ro'] = "";
$text['label-edit-recording_name']['ru-ru'] = "Укажите: название записи";
$text['label-edit-recording_name']['sv-se'] = "Ange: Namn på inspelning";
$text['label-edit-recording_name']['uk-ua'] = "";

$text['label-edit-recording_voice']['en-us'] = "Please provide: Voice";
$text['label-edit-recording_voice']['en-gb'] = "Please provide: Voice";
$text['label-edit-recording_voice']['es-cl'] = "";
$text['label-edit-recording_voice']['pt-pt'] = "";
$text['label-edit-recording_voice']['fr-fr'] = "";
$text['label-edit-recording_voice']['pt-br'] = "";
$text['label-edit-recording_voice']['pl'] = "";
$text['label-edit-recording_voice']['sv-se'] = "";
$text['label-edit-recording_voice']['uk'] = "";
$text['label-edit-recording_voice']['de-at'] = "";

$text['label-edit-is_text_ssml']['en-us'] = "Please choose whether Text is SSML (Speech Synthesis Markup Language) or not";
$text['label-edit-is_text_ssml']['en-gb'] = "Please choose whether Text is SSML (Speech Synthesis Markup Language) or not";
$text['label-edit-is_text_ssml']['es-cl'] = "";
$text['label-edit-is_text_ssml']['pt-pt'] = "";
$text['label-edit-is_text_ssml']['fr-fr'] = "";
$text['label-edit-is_text_ssml']['pt-br'] = "";
$text['label-edit-is_text_ssml']['pl'] = "";
$text['label-edit-is_text_ssml']['sv-se'] = "";
$text['label-edit-is_text_ssml']['uk'] = "";
$text['label-edit-is_text_ssml']['de-at'] = "";

$text['label-edit-recording_ssml']['en-us'] = "Please provide: Text in SSML (Speech Synthesis Markup Language) format";
$text['label-edit-recording_ssml']['en-gb'] = "Please provide: Text in SSML (Speech Synthesis Markup Language) format)";
$text['label-edit-recording_ssml']['es-cl'] = "";
$text['label-edit-recording_ssml']['pt-pt'] = "";
$text['label-edit-recording_ssml']['fr-fr'] = "";
$text['label-edit-recording_ssml']['pt-br'] = "";
$text['label-edit-recording_ssml']['pl'] = "";
$text['label-edit-recording_ssml']['sv-se'] = "";
$text['label-edit-recording_ssml']['uk'] = "";
$text['label-edit-recording_ssml']['de-at'] = "";

$text['label-edit-recording_text']['en-us'] = "Please provide: Text";
$text['label-edit-recording_text']['en-gb'] = "Please provide: Text";
$text['label-edit-recording_text']['es-cl'] = "";
$text['label-edit-recording_text']['pt-pt'] = "";
$text['label-edit-recording_text']['fr-fr'] = "";
$text['label-edit-recording_text']['pt-br'] = "";
$text['label-edit-recording_text']['pl'] = "";
$text['label-edit-recording_text']['sv-se'] = "";
$text['label-edit-recording_text']['uk'] = "";
$text['label-edit-recording_text']['de-at'] = "";

$text['label-edit-pitch']['en-us'] = "Please provide: Pitch";
$text['label-edit-pitch']['en-gb'] = "Please provide: Pitch";
$text['label-edit-pitch']['es-cl'] = "";
$text['label-edit-pitch']['pt-pt'] = "";
$text['label-edit-pitch']['fr-fr'] = "";
$text['label-edit-pitch']['pt-br'] = "";
$text['label-edit-pitch']['pl'] = "";
$text['label-edit-pitch']['sv-se'] = "";
$text['label-edit-pitch']['uk'] = "";
$text['label-edit-pitch']['de-at'] = "";

$text['label-edit-speaking_rate']['en-us'] = "Please provide: Speaking Rate";
$text['label-edit-speaking_rate']['en-gb'] = "Please provide: Speaking Rate";
$text['label-edit-speaking_rate']['es-cl'] = "";
$text['label-edit-speaking_rate']['pt-pt'] = "";
$text['label-edit-speaking_rate']['fr-fr'] = "";
$text['label-edit-speaking_rate']['pt-br'] = "";
$text['label-edit-speaking_rate']['pl'] = "";
$text['label-edit-speaking_rate']['sv-se'] = "";
$text['label-edit-speaking_rate']['uk'] = "";
$text['label-edit-speaking_rate']['de-at'] = "";

$text['description-recording_name']['en-us'] = "A name for the recording.";
$text['description-recording_name']['en-gb'] = "A name for the recording.";
$text['description-recording_name']['ar-eg'] = "";
$text['description-recording_name']['de-at'] = "Ein Name für die Aufnahme."; //copied from de-de
$text['description-recording_name']['de-ch'] = "Ein Name für die Aufnahme."; //copied from de-de
$text['description-recording_name']['de-de'] = "Ein Name für die Aufnahme.";
$text['description-recording_name']['es-cl'] = "Nombre de la grabación.";
$text['description-recording_name']['es-mx'] = "Nombre de la grabación."; //copied from es-cl
$text['description-recording_name']['fr-ca'] = "Nom de l'enregistrement."; //copied from fr-fr
$text['description-recording_name']['fr-fr'] = "Nom de l'enregistrement.";
$text['description-recording_name']['he-il'] = "שם להקלטה לא מנותח.";
$text['description-recording_name']['it-it'] = "Un nome per la registrazione.";
$text['description-recording_name']['nl-nl'] = "Een naam voor de opname.";
$text['description-recording_name']['pl-pl'] = "Nazwa nagrania.";
$text['description-recording_name']['pt-br'] = "Nome da gravação:";
$text['description-recording_name']['pt-pt'] = "Nome da gravação.";
$text['description-recording_name']['ro-ro'] = "";
$text['description-recording_name']['ru-ru'] = "Имя для записи.";
$text['description-recording_name']['sv-se'] = "Namn på Inspelning.";
$text['description-recording_name']['uk-ua'] = "Ім'я для запису.";

$text['description-recording_voice']['en-us'] = "The voice to be used for the speech.";
$text['description-recording_voice']['en-gb'] = "The voice to be used for the speech.";
$text['description-recording_voice']['es-cl'] = "";
$text['description-recording_voice']['pt-pt'] = "";
$text['description-recording_voice']['fr-fr'] = "";
$text['description-recording_voice']['pt-br'] = "";
$text['description-recording_voice']['pl'] = "";
$text['description-recording_voice']['sv-se'] = "";
$text['description-recording_voice']['uk'] = "";
$text['description-recording_voice']['de-at'] = "";

$text['description-is_text_ssml']['en-us'] = "Is the Text in SSML (Speech Synthesis Markup Language) format?";
$text['description-is_text_ssml']['en-gb'] = "Is the Text in SSML (Speech Synthesis Markup Language) format?";
$text['description-is_text_ssml']['es-cl'] = "";
$text['description-is_text_ssml']['pt-pt'] = "";
$text['description-is_text_ssml']['fr-fr'] = "";
$text['description-is_text_ssml']['pt-br'] = "";
$text['description-is_text_ssml']['pl'] = "";
$text['description-is_text_ssml']['sv-se'] = "";
$text['description-is_text_ssml']['uk'] = "";
$text['description-is_text_ssml']['de-at'] = "";

$text['description-recording_text']['en-us'] = "The Text (or SSML) to be spoken.";
$text['description-recording_text']['en-gb'] = "The Text (or SSML) to be spoken.";
$text['description-recording_text']['es-cl'] = "";
$text['description-recording_text']['pt-pt'] = "";
$text['description-recording_text']['fr-fr'] = "";
$text['description-recording_text']['pt-br'] = "";
$text['description-recording_text']['pl'] = "";
$text['description-recording_text']['sv-se'] = "";
$text['description-recording_text']['uk'] = "";
$text['description-recording_text']['de-at'] = "";

$text['description-pitch']['en-us'] = "Adjust the pitch of the voice, ranging from 0.0 to 2.0, 1.0 being normal.";
$text['description-pitch']['en-gb'] = "Adjust the pitch of the voice, ranging from 0.0 to 2.0, 1.0 being normal.";
$text['description-pitch']['es-cl'] = "";
$text['description-pitch']['pt-pt'] = "";
$text['description-pitch']['fr-fr'] = "";
$text['description-pitch']['pt-br'] = "";
$text['description-pitch']['pl'] = "";
$text['description-pitch']['sv-se'] = "";
$text['description-pitch']['uk'] = "";
$text['description-pitch']['de-at'] = "";

$text['description-speaking_rate']['en-us'] = "Adjust the speaking rate, ranging from 0.0 to 3.0, 1.0 being normal.";
$text['description-speaking_rate']['en-gb'] = "Adjust the speaking rate, ranging from 0.0 to 3.0, 1.0 being normal.";
$text['description-speaking_rate']['es-cl'] = "";
$text['description-speaking_rate']['pt-pt'] = "";
$text['description-speaking_rate']['fr-fr'] = "";
$text['description-speaking_rate']['pt-br'] = "";
$text['description-speaking_rate']['pl'] = "";
$text['description-speaking_rate']['sv-se'] = "";
$text['description-speaking_rate']['uk'] = "";
$text['description-speaking_rate']['de-at'] = "";

$text['description-generated_ssml']['en-us'] = "SSML generated from the Text above. You can use this and customize it and enter it in the Text above (make sure to select 'Yes' for 'Is Text SSML').";
$text['description-generated_ssml']['en-gb'] = "SSML generated from the Text above. You can use this and customize it and enter it in the Text above (make sure to select 'Yes' for 'Is Text SSML').";
$text['description-generated_ssml']['es-cl'] = "";
$text['description-generated_ssml']['pt-pt'] = "";
$text['description-generated_ssml']['fr-fr'] = "";
$text['description-generated_ssml']['pt-br'] = "";
$text['description-generated_ssml']['pl'] = "";
$text['description-generated_ssml']['sv-se'] = "";
$text['description-generated_ssml']['uk'] = "";
$text['description-generated_ssml']['de-at'] = "";

$text['message-invalid_recording_filename']['en-us'] = "Invalid Recording file name";
$text['message-invalid_recording_filename']['en-gb'] = "Invalid Recording file name";
$text['message-invalid_recording_filename']['es-cl'] = "";
$text['message-invalid_recording_filename']['pt-pt'] = "";
$text['message-invalid_recording_filename']['fr-fr'] = "";
$text['message-invalid_recording_filename']['pt-br'] = "";
$text['message-invalid_recording_filename']['pl'] = "";
$text['message-invalid_recording_filename']['sv-se'] = "";
$text['message-invalid_recording_filename']['uk'] = "";
$text['message-invalid_recording_filename']['de-at'] = "";

$text['message-unable_to_generate_audio']['en-us'] = "Unable to generate TTS audio, check Text and Azure Subscription Key";
$text['message-unable_to_generate_audio']['en-gb'] = "Unable to generate TTS audio, check Text and Azure Subscription Key";
$text['message-unable_to_generate_audio']['es-cl'] = "";
$text['message-unable_to_generate_audio']['pt-pt'] = "";
$text['message-unable_to_generate_audio']['fr-fr'] = "";
$text['message-unable_to_generate_audio']['pt-br'] = "";
$text['message-unable_to_generate_audio']['pl'] = "";
$text['message-unable_to_generate_audio']['sv-se'] = "";
$text['message-unable_to_generate_audio']['uk'] = "";
$text['message-unable_to_generate_audio']['de-at'] = "";

?>
